### ISSUE TITLE
Suggested papers

### ISSUE THREAD

**Issue by NielsRogge** [wvangansbeke/Self-Supervised-Learning-Overview#1]
Hi,

Recently, computer vision seems to have its BERT-moment, realizing that masked image modeling works great as a self-supervised pretraining objective for representation learning. Relevant papers:

- SiT: https://arxiv.org/abs/2104.03602
- BEiT: https://arxiv.org/abs/2106.08254
- MAE: https://arxiv.org/abs/2111.06377
- SimMIM: https://arxiv.org/abs/2111.09886

**Comment by wvangansbeke** [comment]
Hi @NielsRogge,

Thanks for mentioning these works. I'm aware of them but haven't found the time to add them to the list. Planning to do this later this week (pull requests are also welcome). There are a few other works I should add as well. I appreciate any feedback.

**Comment by wvangansbeke** [comment]
Hi,

Added a few. Will add more in the future. Thanks!
